using System.Collections.Generic;
using System.Windows;
using DataObjects;
using LogicLayer;

namespace PresentationLayer
{
    /// <summary>
    /// Interaction logic for Cart.xaml
    /// </summary>
    public partial class PgCart
    {
        private decimal _subTotal = 0;
        private readonly ICartManager _cartManager;
        private readonly List<InstrumentVm> _cartItems;
        private readonly Employee _user;


        public PgCart(Employee user)
        {
            InitializeComponent();
            _cartManager = new CartManager();
            _cartItems = _cartManager.GetAllInCart();
            _user = user;
        }

        private void dgCart_Loaded(object sender, RoutedEventArgs e)
        {
            DgCart.ItemsSource = _cartItems;
        }

        private void DgCart_AutoGeneratedColumns(object sender, System.EventArgs e)
        {
            DgCart.Columns.RemoveAt(1);
            DgCart.Columns.RemoveAt(2);
            DgCart.Columns.RemoveAt(2);
            DgCart.Columns.RemoveAt(6);
            DgCart.Columns[2].Header = "ID";
            DgCart.Columns[3].Header = "Type";
            DgCart.Columns[5].Header = "Brand";
            DgCart.Columns[0].Header = "Rental Term";
            DgCart.Columns[1].Header = "Rental Fee";
            DgCart.Columns[4].Header = "Status";
            DgCart.Columns[6].Header = "Price";
            DgCart.Columns[0].Width = 100;
            DgCart.Columns[1].Width = 95;
            DgCart.Columns[2].Width = 90;
            DgCart.Columns[3].Width = 100;
            DgCart.Columns[4].Width = 100;
            DgCart.Columns[5].Width = 70;
            DgCart.Columns[6].Width = 100;
        }

        private void GetTaxAndTotal()
        {
            decimal tax = _subTotal *  0.07M;
            decimal total = _subTotal + tax;
            TxtTax.Text = tax.ToString("c");
            TxtTotal.Text = total.ToString("c");
        }

        private void Page_Loaded(object sender, RoutedEventArgs e)
        {
            foreach (var instrumentVm in _cartItems)
            {
                _subTotal += instrumentVm.Price;
            }
            GetTaxAndTotal();
            TxtEmployee.Text = _user.FirstName;
        }
    }
}
