using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using DataObjects;
using LogicLayer;

namespace PresentationLayer
{
    /// <summary>
    /// Interaction logic for pgInvoiceDetails.xaml
    /// </summary>
    public partial class pgInvoiceDetails : Page
    {
        private readonly Invoice _invoice;
        private List<InvoiceLineVM> _invoiceLines;
        private readonly IInvoiceLineManager _invoiceLineManager;
        public pgInvoiceDetails(Invoice invoice)
        {
            InitializeComponent();
            _invoiceLineManager = new InvoiceLineManager();
            _invoice = invoice;
        }


        private void Page_Loaded(object sender, RoutedEventArgs e)
        {
            TxtCustomer.Text = _invoice.CustomerLastName + ", " + _invoice.CustomerFirstName;
            TxtEmployee.Text = _invoice.EmployeeLastName + ", " + _invoice.EmployeeFirstName;
            TxtDate.Text = _invoice.TransactionDate.ToShortDateString();
            TxtTotal.Text = _invoice.TotalString;
            getAllInvoiceLInes();
        }


        private void getAllInvoiceLInes()
        {
            try
            {
                _invoiceLines = _invoiceLineManager.GetAllInvoiceLInesByInvoiceID(_invoice.InvoiceId);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message + "\n\n" + ex.InnerException?.Message);
            }
        }

        private void DgInvoiceLine_Loaded(object sender, RoutedEventArgs e)
        {
            DgInvoiceLine.IsReadOnly = true;
            DgInvoiceLine.ItemsSource = _invoiceLines;
        }

        private void DgInvoiceLine_AutoGeneratedColumns(object sender, EventArgs e)
        {
            DgInvoiceLine.Columns.RemoveAt(7);
            DgInvoiceLine.Columns.RemoveAt(6);
            DgInvoiceLine.Columns.RemoveAt(5);
            DgInvoiceLine.Columns.RemoveAt(4);
            DgInvoiceLine.Columns.RemoveAt(3);
            DgInvoiceLine.Columns.RemoveAt(2);
            DgInvoiceLine.Columns[0].Header = "Instrument Type";
            DgInvoiceLine.Columns[1].Header = "Brand";
            DgInvoiceLine.Columns[2].Header = "Price";
        }
    }
}
