using System;
using System.Windows;
using System.Windows.Controls;
using DataObjects;
using LogicLayer;

namespace PresentationLayer
{
    /// <summary>
    /// Interaction logic for pgInvoiceList.xaml
    /// </summary>
    public partial class pgInvoiceList : Page
    {
        private readonly IInvoiceManager _invoiceManager;

        public pgInvoiceList()
        {
            InitializeComponent();
            _invoiceManager = new InvoiceManager();
        }

        private void DgInvoiceList_Loaded(object sender, RoutedEventArgs e)
        {
            try
            {
                DgInvoiceList.ItemsSource = _invoiceManager.GetAllInvoices();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message + "\n\n" + ex.InnerException?.Message);
            }
        }

        private void DgInvoiceList_AutoGeneratedColumns(object sender, EventArgs e)
        {
            DgInvoiceList.Columns.RemoveAt(8);
            DgInvoiceList.Columns.RemoveAt(5);
            DgInvoiceList.Columns.RemoveAt(4);
            DgInvoiceList.Columns.RemoveAt(2);
            DgInvoiceList.Columns.RemoveAt(1);
            DgInvoiceList.Columns[0].Header = "Invoice ID";
            DgInvoiceList.Columns[3].Header = "Date";
            DgInvoiceList.Columns[4].Header = "Invoice Total";
        }

        private void DgInvoiceList_MouseDoubleClick(object sender, System.Windows.Input.MouseButtonEventArgs e)
        {
            this.NavigationService?.Navigate(new pgInvoiceDetails((Invoice) DgInvoiceList.SelectedItem));
        }
    }
}
